# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/HyprMXMobile/Cocoapod-Specs.git'

target 'reactNativeCustom' do
	
  pod 'HyprMediate', '2.5'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeCustom

  target 'reactNativeCustom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'reactNativeCustomTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'reactNativeCustom-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for reactNativeCustom-tvOS

  target 'reactNativeCustom-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
